### ISSUE TITLE
Device type error

### ISSUE THREAD

**Issue by Cluade** [danielhavir/capsule-network#5]
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/CIFAR/cifar-10-python.tar.gz
Files already downloaded and verified
######## Using CIFAR dataset ########
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    caps_net = CapsNetTrainer(loaders, args.batch_size, args.learning_rate, args.num_routing, args.lr_decay, device=device, multi_gpu=args.multi_gpu)
  File "/home/centos/Capsule/Capsule_CESAM_detection/trainer.py", line 27, in __init__
    self.net = CapsuleNetwork(img_shape=img_shape, channels=256, primary_dim=8, num_classes=10, out_dim=16, num_routing=num_routing, device=self.device).to(self.device)
  File "/home/centos/anaconda3/envs/newtorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 393, in to
    return self._apply(lambda t: t.to(device))
  File "/home/centos/anaconda3/envs/newtorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/home/centos/anaconda3/envs/newtorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/home/centos/anaconda3/envs/newtorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 393, in <lambda>
    return self._apply(lambda t: t.to(device))
TypeError: to() received an invalid combination of arguments - got (device), but expected one of:
 * (torch.device device, torch.dtype dtype)
 * (torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (!device!)
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!device!)

**Comment by Cluade** [comment]
Resolved thank you
